global using BasicBlazorLibrary.Components.BaseClasses;
global using BasicBlazorLibrary.Components.Basic;
global using BasicBlazorLibrary.Helpers;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses; //so i can have access to the exceptions when needed.
global using CommonBasicLibraries.CollectionClasses;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Phase02SinglePlayerFarmThemesPlayersModes.Components;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using cc1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using css1 = BasicBlazorLibrary.CssHelpers.AllCssClasses; //so i can have intellisense completely from c# if i want.
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using Phase02SinglePlayerFarmThemesPlayersModes.Services.Crops;
global using Phase02SinglePlayerFarmThemesPlayersModes.Services.Trees;
global using Phase02SinglePlayerFarmThemesPlayersModes.Data.General;
global using Phase02SinglePlayerFarmThemesPlayersModes.Services.General;
global using Phase02SinglePlayerFarmThemesPlayersModes.Services.Animals;
global using Phase02SinglePlayerFarmThemesPlayersModes.Services.Workshops;
global using Phase02SinglePlayerFarmThemesPlayersModes.Services.Workers;
global using Phase02SinglePlayerFarmThemesPlayersModes.Data.Worksites;
global using Phase02SinglePlayerFarmThemesPlayersModes.Services.Worksites;
global using Phase02SinglePlayerFarmThemesPlayersModes;
global using Phase02SinglePlayerFarmThemesPlayersModes.Data.Crops;
global using Phase02SinglePlayerFarmThemesPlayersModes.Data.Trees;
global using Phase02SinglePlayerFarmThemesPlayersModes.Data.Animals;
global using Phase02SinglePlayerFarmThemesPlayersModes.Data.Workshops;
global using Phase02SinglePlayerFarmThemesPlayersModes.Data.Workers;
global using CommonBasicLibraries.BasicUIProcesses;
